### PR TITLE
Add an optional TargetConn to RPCAuthInput

### PR DESCRIPTION
**Pull request by stvnrhodes**
We're finding cases where we want the sansshell proxy to make gRPC calls to the target sansshell server as part of gathering input for policy evaluation. For example, for MPA we want the proxy to call out to the server to check if there's any MPA approval for a request.

The ways of doing this in RPCAuthzHook without adding it to RPCAuthInput get very hacky. It's possible to pull out the hosts's address and dial it, but then you're establishing a separate redundant connection and you need to replicate dial options around things like authentication and metrics.

We can't change the hook interface, so our two options are adding a new field to RPCAuthInput or putting the connection into the context. Putting it into the context is possible but we should be putting "request-scoped data that transits processes and API boundaries" in there and a grpc connection doesn't fit that model. We're left with the new RPCAuthInput field as the best option. This PR introduces the first field in RPCAuthInput that's meant purely for use by RPCAuthzHooks and not for policy evaluation.

Part of https://github.com/Snowflake-Labs/sansshell/issues/346

### CODE REVIEW

**Comment by stvnrhodes** [comment]
I left this in draft for a couple weeks as I thought through the consequences of sticking data not meant for OPA evaluation into rpcauthinput. This still seems like the best option for giving a way for proxy to talk to the host.

**Comment by sfc-gh-elinardi** [comment]
@stvnrhodes RPCAuthInput is logged on places like https://github.com/Snowflake-Labs/sansshell/blob/5f1ff80b473140bc3edb92b16b317f4008d062d3/auth/opa/rpcauth/rpcauth.go#L107. How would the connection look like in the logs?

**Comment by stvnrhodes** [comment]
The `json:"-"` struct tag makes the logging library skip the new field, https://github.com/go-logr/logr/blob/10d92fc5ec4e26005e978dd3da7f9bd10f63bf1e/funcr/funcr.go#L465

Here's a log message to confirm:

```
2023/11/11 21:26:05 rpcauth.go:147: sanshell-proxy: "level"=0 "msg"="authz policy evaluation result" "method"="/Proxy.Proxy/Proxy" "peer"={"net":{"network":"tcp","address":"127.0.0.1","port":"38064"},"cert":{"subject":"CN=sanssh,OU=group1+OU=group2,O=Acme Co","issuer":"O=Acme Co","dnsnames":[],"spiffeid":""},"principal":null} "authorizationResult"=true "input"={"method":"/LocalFile.LocalFile/Read","message":[123,34,102,105,108,101,34,58,123,34,102,105,108,101,110,97,109,101,34,58,34,47,101,116,99,47,104,111,115,116,115,34,125,125],"type":"LocalFile.ReadActionRequest","metadata":{":authority":["localhost:50043"],"content-type":["application/grpc"],"user-agent":["grpc-go/1.59.0"]},"peer":{"net":{"network":"tcp","address":"127.0.0.1","port":"38064"},"cert":{"subject":"CN=sanssh,OU=group1+OU=group2,O=Acme Co","issuer":"O=Acme Co","dnsnames":[],"spiffeid":""},"principal":{"id":"sanssh","groups":["group1","group2"]}},"host":{"net":{"network":"tcp","address":"127.0.0.1","port":"50042"},"cert":{"subject":"CN=sansshell-server,OU=group2+OU=group3,O=Acme Co","issuer":"O=Acme Co","dnsnames":["localhost","bufnet"],"spiffeid":""},"principal":null},"approvers":[],"environment":{"non_host_policy_check":true},"extensions":[]} "denialHints"=[]
```

**Comment by sfc-gh-elinardi** [comment]
> The `json:"-"` struct tag makes the logging library skip the new field, [go-logr/logr@`10d92fc`/funcr/funcr.go#L465](https://github.com/go-logr/logr/blob/10d92fc5ec4e26005e978dd3da7f9bd10f63bf1e/funcr/funcr.go#L465)
> 
> Here's a log message to confirm:
> 
> ```
> 2023/11/11 21:26:05 rpcauth.go:147: sanshell-proxy: "level"=0 "msg"="authz policy evaluation result" "method"="/Proxy.Proxy/Proxy" "peer"={"net":{"network":"tcp","address":"127.0.0.1","port":"38064"},"cert":{"subject":"CN=sanssh,OU=group1+OU=group2,O=Acme Co","issuer":"O=Acme Co","dnsnames":[],"spiffeid":""},"principal":null} "authorizationResult"=true "input"={"method":"/LocalFile.LocalFile/Read","message":[123,34,102,105,108,101,34,58,123,34,102,105,108,101,110,97,109,101,34,58,34,47,101,116,99,47,104,111,115,116,115,34,125,125],"type":"LocalFile.ReadActionRequest","metadata":{":authority":["localhost:50043"],"content-type":["application/grpc"],"user-agent":["grpc-go/1.59.0"]},"peer":{"net":{"network":"tcp","address":"127.0.0.1","port":"38064"},"cert":{"subject":"CN=sanssh,OU=group1+OU=group2,O=Acme Co","issuer":"O=Acme Co","dnsnames":[],"spiffeid":""},"principal":{"id":"sanssh","groups":["group1","group2"]}},"host":{"net":{"network":"tcp","address":"127.0.0.1","port":"50042"},"cert":{"subject":"CN=sansshell-server,OU=group2+OU=group3,O=Acme Co","issuer":"O=Acme Co","dnsnames":["localhost","bufnet"],"spiffeid":""},"principal":null},"approvers":[],"environment":{"non_host_policy_check":true},"extensions":[]} "denialHints"=[]
> ```

Ah my bad I overlooked the json tag.

**Review by sfc-gh-elinardi — APPROVED** [review]

**Pull request merged**
